version: '3.9'

services:
  postgres:
      image: postgres
      container_name: ${DB_HOST}
      restart: on-failure
      environment: 
          - POSTGRES_DB=${DB_NAME}
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
      networks: 
          - main
      ports: 
          - "5432:5432"
      volumes: 
          - ./data/postgres:/var/lib/postgresql/data 
  
  app:
      build: .
      container_name: app
      restart: on-failure
      command: sh -c "python3 manage.py makemigrations && 
                      python3 manage.py migrate --no-input && 
                      python3 manage.py collectstatic --no-input && 
                      uwsgi --ini uwsgi.ini"
      depends_on: 
          - postgres
      expose: 
          - "8000"
      networks:
          - main
      volumes: 
          - .:/code/
          - ./static:/app/static
          - ./media:/app/media

  nginx:
      image: nginx
      container_name: nginx
      command: nginx -g 'daemon off;'
      restart: on-failure
      depends_on:
          - app
      networks: 
          - main
      ports: 
          - "80:80"
      volumes: 
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./media:/app/media
          - ./static:/app/static

networks:
  main:

volumes:
  static:

  media:

  data: